<h1>Test</h1>
<?= $this->method; ?>
<ul>
<li>Param: <?= $this->escapeHtml($this->param); ?></li>
<li>Plugin: <?= $this->pluginVar; ?></li>
<li><a href="<?= $this->url('test/main', ['action' => 'json']); ?>">JSON</a></li>
<li><a href="<?= $this->url('test/main', ['action' => 'end']); ?>">The End</a></li>
<li><a href="<?= $this->url('test/main', ['action' => 'pdf']); ?>">Alice in Wonderland</a></li>
<li>Test Service 2: <?= $this->s2; ?></li>
<li>Test Service 2=1: <?= implode(',', $this->s1); ?></li>
</ul>
