<h1>Test</h1>
<?= $this->method; ?>
<ul>
<li>Param: <?= $this->escapeHtml($this->param); ?></li>
<li>Plugin: <?= $this->pluginVar; ?></li>
<li><a href="<?= $this->url('test/main', ['action' => 'json']); ?>">JSON</a></li>
<li><a href="<?= $this->url('test/main', ['action' => 'json-model']); ?>">JSON Model</a></li>
<li><a href="<?= $this->url('test/main', ['action' => 'end']); ?>">The End</a></li>
<li><a href="<?= $this->url('test/main', ['action' => 'pdf']); ?>">Alice in Wonderland</a></li>
<li>Test Service 2: <?= $this->s2; ?></li>
<li>Test Service 1: <pre><?= implode(PHP_EOL, $this->s1); ?></pre></li>
</ul>
<?php foreach ($this->results as $row) : ?>
<?php \Zend\Debug\Debug::dump($row); ?>
<?php endforeach; ?>
